In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

%matplotlib inline

df1 = pd.read_csv('Thursday-01-03-2018_TrafficForML_CICFlowMeter.csv', low_memory=False)
df2 = pd.read_csv('Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv', low_memory=False)

df = pd.concat([df1,df2])

del df['Timestamp'] 

df['keep'] = df.iloc[:, 0:-1].apply(
    lambda row: pd.to_numeric(row, errors='coerce').notnull().all(),
    axis=1
)

df = df.replace([np.inf, -np.inf], np.nan)
df = df[df['keep']]
del df['keep']

df = df.dropna()
df = df.reset_index(drop=True)

df.shape

(1368729, 79)

In [5]:
X = df.iloc[:, :-1].values #features are all but last column
y = df.iloc[:, 78].values #label is last column

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[235144      0      0   9425]
 [     0   8438      1      0]
 [     0      0   2200      0]
 [ 11710      0      0   6828]]
                       precision    recall  f1-score   support

               Benign       0.95      0.96      0.96    244569
DoS attacks-GoldenEye       1.00      1.00      1.00      8439
DoS attacks-Slowloris       1.00      1.00      1.00      2200
        Infilteration       0.42      0.37      0.39     18538

             accuracy                           0.92    273746
            macro avg       0.84      0.83      0.84    273746
         weighted avg       0.92      0.92      0.92    273746

